# DOCKER_VERSION 0.9.0
# VERSION 0.1.0

FROM edpaget/passenger:4.0
MAINTAINER Edward Paget <ed@zooniverse.org>

RUN DEBIAN_FRONTEND=noninteractive apt-get -y -q install build-essential ruby1.8.7 ruby1.8.7-dev imagemagick libsqlite3-dev libmagickwand-dev libcurl3 libxml2 libxslt1-dev libcurl4-gnutls-dev git-core mysql-client libmysqlclient-dev

RUN gem install bundler
WORKDIR /rails
ADD Gemfile /rails/Gemfile
ADD Gemfile.lock /rails/Gemfile.lock
ADD /vendor/ /rails/vendor
RUN bundle install --without development test

ADD ./ /rails
ADD docker/site.conf /etc/nginx/sites-enabled/site.conf

VOLUME ["/rails/log"]
